spring:
  application:
    name: bookshop_eureka_server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG